pipeline {
    agent any
    stages {
        stage("Pull code") {
            steps {
                checkout scm
            }
        }
        stage("Download dependencies") {
            steps {
                dir ("./frontend"){
                    sh "npm install"
                }
            }
        }
        stage("Make env") {
            steps {
                dir ("./frontend"){
                    withCredentials([file(credentialsId: 'ITSUMMARYSHEET_ENV', variable: 'FRONTEND_ENV')]) {
                        script {
                            writeFile(file: '.env', text: readFile(FRONTEND_ENV))
                        }
                    }
                }
            }
        }
        stage("Build frontend") {
            steps {
                dir ("./frontend"){
                    sh "npm run build"
                }
            }
        }
    }
}