version: "3"
services:
  backend:
    container_name: "itsummarysheet-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    networks:
      - itsummarysheet-network
    restart: always
  frontend:
    container_name: "itsummarysheet-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "80:4173"
      - "443:4173"
    volumes:
      - ./frontend:/frontend
    networks:
      - itsummarysheet-network
    restart: always
networks:
  itsummarysheet-network:
    name: itsummarysheet-network
